stages:
  preprocess:
    cmd: python src/preprocessing.py
    deps:
      - src/preprocessing.py
      - data/raw/train/batch_1.csv
      - data/raw/train/batch_2.csv
      - data/raw/train/batch_3.csv
      - data/raw/train/batch_4.csv
    params:
      - preprocess
    outs:
      - data/processed/:
          cache: true

  train_mlflow:
    cmd: python src/modeling_mlflow.py
    deps:
      - src/modeling_mlflow.py
      - data/processed/batch_1_X_processed.csv
      - data/processed/batch_1_y_processed.csv
      - data/processed/batch_2_X_processed.csv
      - data/processed/batch_2_y_processed.csv
      - data/processed/batch_3_X_processed.csv
      - data/processed/batch_3_y_processed.csv
      - data/processed/batch_4_X_processed.csv
      - data/processed/batch_4_y_processed.csv
    params:
      - train
    outs:
      - models/:
          cache: true
      - mlruns/:
          cache: false

  evaluate:
    cmd: python src/batch_evaluation.py
    deps:
      - src/batch_evaluation.py
      - models/batch_1/metadata.json
      - models/batch_2/metadata.json
      - models/batch_3/metadata.json
      - models/batch_4/metadata.json
    outs:
      - reports/batch_analysis/:
          cache: false